### ISSUE TITLE
Design Review Epic: Grid, PDP, App, Cart, MiniCart, Desktop & Mobile

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-next-starterkit#258]
# TopNav - desktop
- [ ] ~~- TopNav should open on _hover_~~
- [ ] ~~- On hover, show the underline  the category~~
- [ ] ~~- Remove the caret V ^ symbol~~

# Nav tag menu - mobile
- [x] - Remove underlines
- [ ] V2: Paging by subcategories: https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/screen/5ace3cc64b0cf5af3b1964ff https://reactioncommerce.slack.com/files/U934TSM0T/FCM39PSJE/menu-animation.gif

# Breadcrumbs
- [x] - Mobile breadcrumbs on Grid - center
- [x] - Mobile breadcrumbs on PDP - hide them

# Grid
- [x] - Padding above the dropdown menus
- [x] - Dropdown menu style is off
- [x] - 1.2 em lineheight for long 2-line product names
- [x] - Brand name should be font size 14px
- [x] - Product name: line-height 18px
- [x] - Brand line height: 21px

# PDP - Mobile
- [x] - Add to cart button should be full-width
- [ ] - V2: Mobile, size options should be a dropdown
- [x] - Product name is too big!
- [ ] - V2: Change all the order of things in mobile
- [x] - Hide the tags, Hide the breadcrumbs

# PDP - Desktop
- [x] - PDP: Spacing b/w the 2
- [ ] - V2: Photos in the color vars?

# Quantity Input
- [x] the Plus / Minus are too big!!! on PDP input

# Add to Cart button
- [x] Add to Cart color 1999dd

# PDP Grid pagination buttons
- [x] PDP Grid Desktop Next/Prev buttons should be Component Library button

# Desktop - Checkout
- [x] - Minicart: left-align image to the edge

**Comment by rosshadden** [comment]
> PDP Grid Desktop Next/Prev buttons should be Component Library button

I did this, but it's worth noting that neither the buttons originally used nor the component library buttons completely match the design.

- original (before I made the change):
![2018-09-14-01 13 26](https://user-images.githubusercontent.com/669012/45530977-99172b80-b7bb-11e8-98fd-2086cbeefcb6.png)
- from component library (how I have it right now):
![2018-09-14-01 13 49](https://user-images.githubusercontent.com/669012/45530994-ab916500-b7bb-11e8-954b-2323eeead4df.png)
- design document:
![2018-09-14-01 14 42](https://user-images.githubusercontent.com/669012/45531002-b51acd00-b7bb-11e8-9ce9-f1ca70e7ab24.png)

It is possible I am looking at the wrong section (as the text isn't the same either). Assuming I'm not though, what is the intended style?

**Comment by rosshadden** [comment]
These changes would decrease the accessibility and usability of the site, especially on mobile. Thus this is an intentional deviation from the design.:

> - TopNav should open on hover
> - On hover, show the underline the category
> - Remove the caret V ^ symbol

These will require some consideration and refactoring. I have broken them out into their own isolated issues:

> - V2: Paging by subcategories [#282]
> - V2: Mobile, size options should be a dropdown [#283]
> - V2: Change all the order of things in mobile [#284]
> - V2: Photos in the color vars? [#285]
