### ISSUE TITLE
📋 Open source checklist

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-next-starterkit#296]
In order to prep this repository for open source use and consumption, we need to complete this checklist:

## Repository checklist
- [x] Add `.github` directory with pull request template, issue template(s) (1 template for bugs, 1 template for features)
- [x] Add issue template(s): bugs, features
- [x] Add Reaction's standard `LICENSE.md`
- [x] Add Reaction's standard `CODE_OF_CONDUCT.md`
- [x] Add Reaction's standard `CONTRIBUTING.md`
