### ISSUE TITLE
Dead code audit & clean up

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction-next-starterkit#438]
Type: **major**

**Describe the bug**
As this project has evolved we've collected some technical debt that we'd like to start cleaning up. I feel like removing dead code from abandoned features is a great starting point to enhance the overall quality of this project.

**Sections to audit**
- [x] `src/server.js` and any remnants of our first auth attempt code that may still be in `.env.example` or `package.json` files.
- [x]  Components that have been ported to the component-library and are no longer needed.
- [x] `lib/utils/` & `lib/helpers` could be combined into a single dir.
- [x] `lib/stores` verify what MobX store methods/properties are being used.

**Additional context**
The main point of this ticket is to start a convo on cleaning up tech debt and refactoring complex/haphazard feature implementations.
